apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otusMicroservice.fullname" . }}-migrations-configmap
  annotations:
    "helm.sh/hook-weight": "-1"
data:
  V1__init.sql: |
    -- SQL content for initial migration
    CREATE TABLE users
    (
        id         SERIAL PRIMARY KEY,
        username   VARCHAR(255) NOT NULL,
        first_name VARCHAR(255) NOT NULL,
        last_name  VARCHAR(255),
        email      VARCHAR(255) NOT NULL,
        phone      VARCHAR(255)
    );